version: "3"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
      container_name: nodejs
    restart: unless-stopped
    ports:
    — "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
    — mongo
  mongo:
      image: mongo
      ports:
      — "27017:27017"
